// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqssibajqoqmtdpxustg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxc3NpYmFqcW9xbXRkcHh1c3RnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMjI5MjcsImV4cCI6MjA1NTc5ODkyN30.mo6L2PN1rvT0O5U5f5Ubb6pIpR_0-BcY7y-PjN5hBhQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);